"use client";
// eslint-disable-next-line @next/next/no-img-element

import React from "react";
import "../../css/gcs.css";
import "../../css/media.css";
import "../../js/popper.min.js";
import Header from "@/app/header/simpleHeader";
import Footer from "@/app/footer/Footer";

export default function PrivacyPolicy() {
  return (
    <>
      <Header
        logoURL={"/images/logos/gcs-logo-white.png"}
        mobileLogoURL={"/images/logos/fitit-logo.png"}
        altLogo={"Fitit Logo"}
      />
      <section className="margintop" style={{ marginBottom: "100px" }}>
        <div className="container-fluid">
          <div className="container">
            <div className="privacy-policy">
              <h1>Privacy Policy</h1>
              <p>{`At GCS Consultant, accessible from https://gcsconsultant.com/, one of our main priorities is the
                                privacy of our visitors. This Privacy Policy document contains types of information that is
                                collected and recorded by GCS Consultant and how we use it.`}</p>
              <p>{`If you have additional questions or require more information about our Privacy Policy, do not
                                hesitate to contact us through email at privacy@gcsconsultant.com.`}</p>
              <div className="inprivacy">
                <h4>Log Files</h4>
                <p>{`GCS Consultant follows a standard procedure of using log files. These files log visitors when
                                    they visit websites. All hosting companies do this and a part of hosting services'
                                    analytics. The information collected by log files includes internet protocol (IP) addresses,
                                    browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages,
                                    and possibly the number of clicks. These are not linked to any information that is
                                    personally identifiable. The purpose of the information is for analyzing trends,
                                    administering the site, tracking users' movement on the website, and gathering demographic
                                    information.`}</p>
              </div>
              <div className="inprivacy">
                <h4>Cookies and Web Beacons</h4>
                <p>{`Like any other website, GCS Consultant uses 'cookies'. These cookies are used to store
                                    information including visitors' preferences, and the pages on the website that the visitor
                                    accessed or visited. The information is used to optimize the users' experience by
                                    customizing our web page content based on visitors' browser type and/or other information.
                                `}</p>
                <p>{`For more general information on cookies, please read the "What Are Cookies" article on Cookie
                                    Consent website.`}</p>
              </div>
              <div className="inprivacy">
                <h4>Google Analytics</h4>
                <p>{`GCS Consultant uses Google Analytics, a web analytics service provided by Google, Inc.
                                    ("Google"). Google Analytics uses cookies to help us analyze how users use our website. The
                                    information generated by the cookie about your use of the website (including your IP
                                    address) will be transmitted to and stored by Google on servers in the United States. Google
                                    will use this information for the purpose of evaluating your use of the website, compiling
                                    reports on website activity for website operators, and providing other services relating to
                                    website activity and internet usage.`}</p>
              </div>
              <div className="inprivacy">
                <h4>Security</h4>
                <p>{`We take precautions to protect your information. When you submit sensitive information via
                                    the website, your information is protected both online and offline.`}</p>
              </div>
              <div className="inprivacy">
                <h4>Links to Other Sites</h4>
                <p>{`Our website may contain links to other sites that are not operated by us. If you click on a
                                    third-party link, you will be directed to that third party's site. We strongly advise you to
                                    review the Privacy Policy of every site you visit.`}</p>
              </div>
              <div className="inprivacy">
                <h4>{`Children's Information`}</h4>
                <p>{`We do not knowingly collect any Personal Identifiable Information from children under the age
                                    of 13. If you think that your child provided this kind of information on our website, we
                                    strongly encourage you to contact us immediately and we will do our best efforts to promptly
                                    remove such information from our records.`}</p>
              </div>
              <div className="inprivacy">
                <h4>Online Privacy Policy Only</h4>
                <p>{`This Privacy Policy applies only to our online activities and is valid for visitors to our
                                    website with regards to the information that they shared and/or collect in GCS Consultant.
                                    This policy is not applicable to any information collected offline or via channels other
                                    than this website.`}</p>
              </div>
              <div className="inprivacy">
                <h4>Consent</h4>
                <p>{`By using our website, you hereby consent to our Privacy Policy and agree to its terms.`}</p>
              </div>
              <div className="inprivacy">
                <h4>Updates</h4>
                <p>{`This Privacy Policy was last updated on March 30, 2023. If there will be any update,
                                    amendment, or changes to our Privacy Policy then these will be posted on this page.`}</p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <Footer />
    </>
  );
}
