'use strict';function u(f,a,b,c){f.A.sc(f.bb,a,b,c,void 0)}function D(f,a,b,c){f.A.ca?u(f,a,b,c):f.A.pf()._OnMessageFromDOM({type:"event",component:f.bb,handler:a,dispatchOpts:c||null,data:b,responseId:null})}function E(f,a,b){f.A.C(f.bb,a,b)}function I(f,a){for(const [b,c]of a)E(f,b,c)}function J(f){f.Tb||(f.A.Ze(f.ie),f.Tb=!0)}window.Da=class{constructor(f,a){this.A=f;this.bb=a;this.Tb=!1;this.ie=()=>this.ua()}jd(){}ua(){}};function L(f){-1!==f.Sa&&(self.clearTimeout(f.Sa),f.Sa=-1)}
window.Qe=class{constructor(f,a){this.Pc=f;this.Jg=a;this.Sa=-1;this.Ub=-Infinity;this.je=()=>{this.Sa=-1;this.Ub=Date.now();this.hb=!0;this.Pc();this.hb=!1};this.Rd=this.hb=!1}c(){L(this);this.je=this.Pc=null}};"use strict";
function N(f,a){const b=a.elementId,c=f.nd(b,a);f.Y.set(b,c);c.style.boxSizing="border-box";a.isVisible||(c.style.display="none");a=f.Cc(c);a.addEventListener("focus",()=>{O(f,"elem-focused",b)});a.addEventListener("blur",()=>{O(f,"elem-blurred",b)});f.Ob&&document.body.appendChild(c)}function P(f,a){E(f,"get-element",b=>{const c=f.Y.get(b.elementId);return a(c,b)})}function O(f,a,b){var c;c||(c={});c.elementId=b;u(f,a,c)}
window.Ce=class extends self.Da{constructor(f,a){super(f,a);this.Y=new Map;this.Ob=!0;I(this,[["create",b=>N(this,b)],["destroy",b=>{{b=b.elementId;const c=this.Y.get(b);this.Ob&&c.parentElement.removeChild(c);this.Y.delete(b)}}],["set-visible",b=>{this.Ob&&(this.Y.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Ob){var c=this.Y.get(b.elementId);c.style.left=b.left+"px";c.style.top=b.top+"px";c.style.width=b.width+"px";c.style.height=b.height+"px";b=b.fontSize;
null!==b&&(c.style.fontSize=b+"em")}}],["update-state",b=>{{const c=this.Y.get(b.elementId);this.yc(c,b)}}],["focus",b=>{{const c=this.Cc(this.Y.get(b.elementId));b.focus?c.focus():c.blur()}}],["set-css-style",b=>{this.Y.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.Y.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.Y.get(b.elementId).removeAttribute(b.name)}]]);P(this,b=>b)}nd(){throw Error("required override");}yc(){throw Error("required override");}Cc(f){return f}};
"use strict";
{const f=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(h){const d=document.createElement("script");d.async=!1;d.type="module";return h.Ug?new Promise(k=>{const l="c3_resolve_"+a;++a;self[l]=k;d.textContent=h.Yg+`\n\nself["${l}"]();`;document.head.appendChild(d)}):new Promise((k,l)=>{d.onload=k;d.onerror=l;d.src=h;document.head.appendChild(d)})}let c=!1,g=!1;function m(){if(!c){try{new Worker("blob://",{get type(){g=!0}})}catch(h){}c=!0}return g}let p=
new Audio;const x={"audio/webm; codecs=opus":!!p.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!p.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!p.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!p.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!p.canPlayType("audio/mp4"),"audio/mpeg":!!p.canPlayType("audio/mpeg")};p=null;async function A(h){h=await B(h);return(new TextDecoder("utf-8")).decode(h)}function B(h){return new Promise((d,
k)=>{const l=new FileReader;l.onload=n=>d(n.target.result);l.onerror=n=>k(n);l.readAsArrayBuffer(h)})}const v=[];let w=0;window.RealFile=window.File;const C=[],H=new Map,z=new Map;let K=0;const F=[];self.runOnStartup=function(h){if("function"!==typeof h)throw Error("runOnStartup called without a function");F.push(h)};const M=new Set(["cordova","playable-ad","instant-games"]);let e=!1;window.ta=class h{constructor(d){this.ca=d.$g;this.oa=null;this.F="";this.fc=d.Xg;this.wb={};this.La=this.vb=null;
this.Rb=[];this.kb=this.G=this.Qa=null;this.Pa=-1;this.Og=()=>this.Rf();this.Oa=[];this.v=d.ke;this.ib="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&m()||(this.ca=!1);if("playable-ad"===this.v||"instant-games"===this.v)this.ca=!1;if("cordova"===this.v&&this.ca)if(/android/i.test(navigator.userAgent)){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],10)||(this.ca=!1)}else this.ca=!1;this.Wb=this.ha=null;"html5"!==
this.v&&"playable-ad"!==this.v||!this.ib||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");"html5"!==this.v||window.isSecureContext||console.warn("[Construct 3] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",k=>this.xf(k));this.C("runtime",
"create-job-worker",()=>this.yf());"cordova"===this.v?document.addEventListener("deviceready",()=>this.Dd(d)):this.Dd(d)}c(){this.zc();this.oa&&(this.oa=this.oa.onmessage=null);this.vb&&(this.vb.terminate(),this.vb=null);this.La&&(this.La.c(),this.La=null);this.G&&(this.G.parentElement.removeChild(this.G),this.G=null)}Le(){return f&&"cordova"===this.v}rc(){const d=navigator.userAgent;return f&&M.has(this.v)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(d)}async Dd(d){"macos-wkwebview"===
this.v&&this.lg();if("playable-ad"===this.v){this.ha=self.c3_base64files;this.Wb={};await this.df();for(let l=0,n=d.Ta.length;l<n;++l){var k=d.Ta[l].toLowerCase();this.Wb.hasOwnProperty(k)?d.Ta[l]={Ug:!0,Yg:this.Wb[k]}:this.ha.hasOwnProperty(k)&&(d.Ta[l]=URL.createObjectURL(this.ha[k]))}}d.Pg?this.F=d.Pg:(k=location.origin,this.F=("null"===k?"file:///":k)+location.pathname,k=this.F.lastIndexOf("/"),-1!==k&&(this.F=this.F.substr(0,k+1)));d.bh&&(this.wb=d.bh);k=new MessageChannel;this.oa=k.port1;this.oa.onmessage=
l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Nf(l));this.kb=new self.Me(this);await Q(this.kb);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ca?await this.rf(d,k.port2):await this.qf(d,k.port2)}Dc(d){d=this.wb.hasOwnProperty(d)?this.wb[d]:d.endsWith("/workermain.js")&&this.wb.hasOwnProperty("workermain.js")?this.wb["workermain.js"]:
"playable-ad"===this.v&&this.ha.hasOwnProperty(d.toLowerCase())?this.ha[d.toLowerCase()]:d;d instanceof Blob&&(d=URL.createObjectURL(d));return d}async lc(d,k,l){if(d.startsWith("blob:"))return new Worker(d,l);if("cordova"===this.v&&this.ib)return d=await this.xb(l.Tg?d:this.fc+d),new Worker(URL.createObjectURL(new Blob([d],{type:"application/javascript"})),l);d=new URL(d,k);if(location.origin!==d.origin){d=await fetch(d);if(!d.ok)throw Error("failed to fetch worker script");d=await d.blob();return new Worker(URL.createObjectURL(d),
l)}return new Worker(d,l)}xa(){return Math.max(window.innerWidth,1)}wa(){return Math.max(window.innerHeight,1)}Ad(d){var k=this.kb;return{baseUrl:this.F,windowInnerWidth:this.xa(),windowInnerHeight:this.wa(),devicePixelRatio:window.devicePixelRatio,isFullscreen:h.Wa(),projectData:d.hh,previewImageBlobs:window.cr_previewImageBlobs||this.ha,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.fh||"",exportType:d.ke,isDebug:-1<
self.location.search.indexOf("debug"),ife:!!self.gh,jobScheduler:{inputPort:k.Vc,outputPort:k.bd,maxNumWorkers:k.Lg},supportedAudioFormats:x,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.fc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.fc+"opus.wasm.wasm",isFileProtocol:this.ib,isiOSCordova:this.Le(),isiOSWebView:this.rc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async rf(d,k){var l=this.Dc(d.ah);this.vb=await this.lc(l,this.F,{type:"module",name:"Runtime",
Tg:!0});this.G=document.createElement("canvas");this.G.style.display="none";l=this.G.transferControlToOffscreen();document.body.appendChild(this.G);window.c3canvas=this.G;let n=d.hd||[],t=d.Ta;n=await Promise.all(n.map(q=>this.Ga(q)));t=await Promise.all(t.map(q=>this.Ga(q)));if("cordova"===this.v)for(let q=0,r=d.jc.length;q<r;++q){const y=d.jc[q],G=y[0];if(G===d.fd||"scriptsInEvents.js"===G||G.endsWith("/scriptsInEvents.js"))y[1]=await this.Ga(G)}this.vb.postMessage(Object.assign(this.Ad(d),{type:"init-runtime",
isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:n,engineScripts:t,projectScripts:d.jc,mainProjectScript:d.fd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,l,...R(this.kb)]);this.Rb=C.map(q=>new q(this));this.zd();self.c3_callFunction=(q,r)=>this.Qa.sf(q,r);"preview"===this.v&&(self.goToLastErrorScript=()=>this.sc("runtime","go-to-last-error-script"))}async qf(d,k){this.G=document.createElement("canvas");this.G.style.display="none";document.body.appendChild(this.G);window.c3canvas=
this.G;this.Rb=C.map(q=>new q(this));this.zd();var l=d.Ta.map(q=>"string"===typeof q?(new URL(q,this.F)).toString():q);Array.isArray(d.hd)&&l.unshift(...d.hd);l=await Promise.all(l.map(q=>this.Ga(q)));await Promise.all(l.map(q=>b(q)));l=self.C3_ProjectScriptsStatus;const n=d.fd,t=d.jc;for(let [q,r]of t)if(r||(r=q),q===n)try{r=await this.Ga(r),await b(r),"preview"!==this.v||l[q]||this.Ld(q,"main script did not run to completion")}catch(y){this.Ld(q,y)}else if("scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))r=
await this.Ga(r),await b(r);"preview"===this.v&&"object"!==typeof self.dh.eh?(this.Kb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(d=Object.assign(this.Ad(d),{isInWorker:!1,messagePort:k,canvas:this.G,runOnStartupFunctions:F}),this.Fd(),this.La=self.C3_CreateRuntime(d),await self.C3_InitRuntime(this.La,d))}Ld(d,
k){this.Kb();console.error(`[Preview] Failed to load project main script (${d}): `,k);alert(`Failed to load project main script (${d}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Fd(){this.Kb()}Kb(){const d=window.Qg;d&&(d.parentElement.removeChild(d),window.Qg=null)}async yf(){const d=await S(this.kb);return{outputPort:d,transferables:[d]}}pf(){if(this.ca)throw Error("not available in worker mode");return this.La}sc(d,k,l,n,t){this.oa.postMessage({type:"event",
component:d,handler:k,dispatchOpts:n||null,data:l,responseId:null},t)}sd(d,k,l,n,t){const q=K++,r=new Promise((y,G)=>{z.set(q,{resolve:y,reject:G})});this.oa.postMessage({type:"event",component:d,handler:k,dispatchOpts:n||null,data:l,responseId:q},t);return r}["_OnMessageFromRuntime"](d){const k=d.type;if("event"===k)return this.Df(d);if("result"===k)this.Vf(d);else if("runtime-ready"===k)this.Wf();else if("alert-error"===k)this.Kb(),alert(d.message);else if("creating-runtime"===k)this.Fd();else throw Error(`unknown message '${k}'`);
}Df(d){const k=d.component,l=d.handler,n=d.data,t=d.responseId;if(d=H.get(k))if(d=d.get(l)){var q=null;try{q=d(n)}catch(r){console.error(`Exception in '${k}' handler '${l}':`,r);null!==t&&this.Jb(t,!1,""+r);return}if(null===t)return q;q&&q.then?q.then(r=>this.Jb(t,!0,r)).catch(r=>{console.error(`Rejection from '${k}' handler '${l}':`,r);this.Jb(t,!1,""+r)}):this.Jb(t,!0,q)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Jb(d,
k,l){let n;l&&l.transferables&&(n=l.transferables);this.oa.postMessage({type:"result",responseId:d,isOk:k,result:l},n)}Vf(d){const k=d.responseId,l=d.isOk;d=d.result;const n=z.get(k);l?n.resolve(d):n.reject(d);z.delete(k)}C(d,k,l){let n=H.get(d);n||(n=new Map,H.set(d,n));if(n.has(k))throw Error(`[DOM] Component '${d}' already has handler '${k}'`);n.set(k,l)}static Ca(d){if(C.includes(d))throw Error("DOM handler already added");C.push(d)}zd(){for(const d of this.Rb)if("runtime"===d.bb){this.Qa=d;return}throw Error("cannot find runtime DOM handler");
}Nf(d){this.sc("debugger","message",d)}Wf(){for(const d of this.Rb)d.jd()}static Wa(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||e)}static Md(d){e=!!d}Ze(d){this.Oa.push(d);this.Nc()}ig(d){d=this.Oa.indexOf(d);if(-1===d)throw Error("invalid callback");this.Oa.splice(d,1);this.Oa.length||this.zc()}Nc(){-1===this.Pa&&this.Oa.length&&(this.Pa=requestAnimationFrame(this.Og))}zc(){-1!==this.Pa&&(cancelAnimationFrame(this.Pa),this.Pa=-1)}Rf(){this.Pa=
-1;for(const d of this.Oa)d();this.Nc()}va(d){this.Qa.va(d)}Fa(d){this.Qa.Fa(d)}Mc(){this.Qa.Mc()}Db(d){this.Qa.Db(d)}Ke(){return!!x["audio/webm; codecs=opus"]}async Hg(d){d=await this.sd("runtime","opus-decode",{arrayBuffer:d},null,[d]);return new Float32Array(d)}Je(d){return/^(?:[a-z\-]+:)?\/\//.test(d)||"data:"===d.substr(0,5)||"blob:"===d.substr(0,5)}rd(d){return!this.Je(d)}async Ga(d){return"cordova"===this.v&&(d.startsWith("file:")||this.ib&&this.rd(d))?(d.startsWith(this.F)&&(d=d.substr(this.F.length)),
d=await this.xb(d),URL.createObjectURL(new Blob([d],{type:"application/javascript"}))):d}async xf(d){const k=d.filename;switch(d.as){case "text":return await this.Be(k);case "buffer":return await this.xb(k);default:throw Error("unsupported type");}}md(d){const k=window.cordova.file.applicationDirectory+"www/"+d.toLowerCase();return new Promise((l,n)=>{window.resolveLocalFileSystemURL(k,t=>{t.file(l,n)},n)})}async Be(d){d=await this.md(d);return await A(d)}Ac(){if(v.length&&!(8<=w)){w++;var d=v.shift();
this.ef(d.filename,d.Zg,d.Sg)}}xb(d){return new Promise((k,l)=>{v.push({filename:d,Zg:n=>{w--;this.Ac();k(n)},Sg:n=>{w--;this.Ac();l(n)}});this.Ac()})}async ef(d,k,l){try{const n=await this.md(d),t=await B(n);k(t)}catch(n){l(n)}}lg(){var d={type:"ready"};if("windows-webview2"===this.v)window.chrome.webview.postMessage(JSON.stringify(d));else if("macos-wkwebview"===this.v)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(d));else throw Error("cannot send wrapper message");}async df(){const d=
[];for(const [k,l]of Object.entries(this.ha))d.push(this.cf(k,l));await Promise.all(d)}async cf(d,k){if("object"===typeof k)this.ha[d]=new Blob([k.str],{type:k.type}),this.Wb[d]=k.str;else{let l=await this.mf(k);l||(l=this.gf(k));this.ha[d]=l}}async mf(d){try{return await (await fetch(d)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
k),null}}gf(d){d=this.cg(d);return this.bf(d.data,d.Vg)}cg(d){var k=d.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=d.substring(k+1);k=d.substring(5,k).split(";");d=k[0]||"";const n=k[2];l="base64"===k[1]||"base64"===n?atob(l):decodeURIComponent(l);return{Vg:d,data:l}}bf(d,k){var l=d.length;let n=l>>2,t=new Uint8Array(l),q=new Uint32Array(t.buffer,0,n),r,y;for(y=r=0;r<n;++r)q[r]=d.charCodeAt(y++)|d.charCodeAt(y++)<<8|d.charCodeAt(y++)<<16|d.charCodeAt(y++)<<24;for(l&=
3;l--;)t[y]=d.charCodeAt(y),++y;return new Blob([t],{type:k})}}}"use strict";
{const f=self.ta;function a(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),c={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},m={dispatchRuntimeEvent:!0};function p(e){return new Promise((h,d)=>{const k=document.createElement("link");k.onload=()=>h(k);k.onerror=l=>d(l);k.rel=
"stylesheet";k.href=e;document.head.appendChild(k)})}function x(e){return new Promise((h,d)=>{const k=new Image;k.onload=()=>h(k);k.onerror=l=>d(l);k.src=e})}async function A(e){e=URL.createObjectURL(e);try{return await x(e)}finally{URL.revokeObjectURL(e)}}function B(e){return new Promise((h,d)=>{let k=new FileReader;k.onload=l=>h(l.target.result);k.onerror=l=>d(l);k.readAsText(e)})}async function v(e,h,d){if(!/firefox/i.test(navigator.userAgent))return await A(e);var k=await B(e);k=(new DOMParser).parseFromString(k,
"image/svg+xml");const l=k.documentElement;if(l.hasAttribute("width")&&l.hasAttribute("height")){const n=l.getAttribute("width"),t=l.getAttribute("height");if(!n.includes("%")&&!t.includes("%"))return await A(e)}l.setAttribute("width",h+"px");l.setAttribute("height",d+"px");k=(new XMLSerializer).serializeToString(k);e=new Blob([k],{type:"image/svg+xml"});return await A(e)}function w(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const C=new Set(["input",
"textarea","datalist","select"]),H=new Set(["canvas","body","html"]);function z(e){H.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function K(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await A(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const h=e.getBoundingClientRect();document.body.removeChild(e);return[h.width,
h.height]}};self.C3_RasterSvgImageBlob=async function(e,h,d,k,l){e=await v(e,h,d);const n=document.createElement("canvas");n.width=k;n.height=l;n.getContext("2d").drawImage(e,0,0,h,d);return n};let F=!1;document.addEventListener("pause",()=>F=!0);document.addEventListener("resume",()=>F=!1);function M(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}f.Ca(class extends self.Da{constructor(e){super(e,"runtime");this.Wd=!0;this.Ra=-1;this.dd="any";this.Nd=this.Od=!1;this.Ka=
this.sb=this.za=null;this.bc=this.ac=0;e.C("canvas","update-size",k=>this.Zf(k));e.C("runtime","invoke-download",k=>this.Lf(k));e.C("runtime","raster-svg-image",k=>this.Sf(k));e.C("runtime","get-svg-image-size",k=>this.Jf(k));e.C("runtime","set-target-orientation",k=>this.Xf(k));e.C("runtime","register-sw",()=>this.Uf());e.C("runtime","post-to-debugger",k=>this.Hd(k));e.C("runtime","go-to-script",k=>this.Hd(k));e.C("runtime","before-start-ticking",()=>this.wf());e.C("runtime","debug-highlight",k=>
this.zf(k));e.C("runtime","enable-device-orientation",()=>this.af());e.C("runtime","enable-device-motion",()=>this.$e());e.C("runtime","add-stylesheet",k=>this.uf(k));e.C("runtime","alert",k=>this.vf(k));e.C("runtime","hide-cordova-splash",()=>this.Kf());const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",k=>{const l=k.target;h.has(l.tagName.toLowerCase())||w(l)||k.preventDefault()});const d=e.G;window.addEventListener("selectstart",z);window.addEventListener("gesturehold",
z);d.addEventListener("selectstart",z);d.addEventListener("gesturehold",z);window.addEventListener("touchstart",z,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",z,{passive:!1}),d.addEventListener("pointerdown",z)):d.addEventListener("touchstart",z);this.pb=0;window.addEventListener("mousedown",k=>{1===k.button&&k.preventDefault()});window.addEventListener("mousewheel",K,{passive:!1});window.addEventListener("wheel",K,{passive:!1});window.addEventListener("resize",
()=>this.$f());window.addEventListener("fullscreenchange",()=>this.Ya());window.addEventListener("webkitfullscreenchange",()=>this.Ya());window.addEventListener("mozfullscreenchange",()=>this.Ya());window.addEventListener("fullscreenerror",k=>this.Ic(k));window.addEventListener("webkitfullscreenerror",k=>this.Ic(k));window.addEventListener("mozfullscreenerror",k=>this.Ic(k));e.rc()&&window.addEventListener("focusout",()=>{{const n=document.activeElement;if(n){var k=n.tagName.toLowerCase();var l=new Set("email number password search tel text url".split(" "));
k="textarea"===k?!0:"input"===k?l.has(n.type.toLowerCase()||"text"):w(n)}else k=!1}k||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=k=>this.bg(k);this.Ma=new Set;this.Xb=new WeakSet;this.na=!1}wf(){"cordova"===this.A.v?(document.addEventListener("pause",()=>this.Lc(!0)),document.addEventListener("resume",()=>this.Lc(!1))):document.addEventListener("visibilitychange",()=>this.Lc(document.hidden));return{isSuspended:!(!document.hidden&&!F)}}jd(){window.addEventListener("focus",()=>
this.$a("window-focus"));window.addEventListener("blur",()=>{this.$a("window-blur",{parentHasFocus:M()});this.pb=0});window.addEventListener("focusin",h=>{h=h.target;(C.has(h.tagName.toLowerCase())||w(h))&&this.$a("keyboard-blur")});window.addEventListener("keydown",h=>this.Gd("keydown",h));window.addEventListener("keyup",h=>this.Gd("keyup",h));window.addEventListener("dblclick",h=>this.Jc("dblclick",h,c));window.addEventListener("wheel",h=>this.Pf(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
h=>{this.Ec(h);this.Za("pointerdown",h)}),this.A.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.sb=new self.Qe(()=>this.kf(),5),this.sb.Rd=!0,window.addEventListener("pointerrawupdate",h=>this.Qf(h))):window.addEventListener("pointermove",h=>this.Za("pointermove",h)),window.addEventListener("pointerup",h=>this.Za("pointerup",h)),window.addEventListener("pointercancel",h=>this.Za("pointercancel",h))):(window.addEventListener("mousedown",h=>{this.Ec(h);this.Kc("pointerdown",
h)}),window.addEventListener("mousemove",h=>this.Kc("pointermove",h)),window.addEventListener("mouseup",h=>this.Kc("pointerup",h)),window.addEventListener("touchstart",h=>{this.Ec(h);this.Ib("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Ib("pointermove",h)),window.addEventListener("touchend",h=>this.Ib("pointerup",h)),window.addEventListener("touchcancel",h=>this.Ib("pointercancel",h)));const e=()=>this.Mc();window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",
e,!0);window.addEventListener("click",e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0)}$a(e,h){u(this,e,h||null,m)}xa(){return this.A.xa()}wa(){return this.A.wa()}$f(){const e=this.xa(),h=this.wa();this.$a("window-resize",{innerWidth:e,innerHeight:h,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Wa()});this.A.rc()&&(-1!==this.Ra&&clearTimeout(this.Ra),this.Id(e,h,0))}jg(e,h,d){-1!==this.Ra&&clearTimeout(this.Ra);this.Ra=setTimeout(()=>this.Id(e,
h,d),48)}Id(e,h,d){const k=this.xa(),l=this.wa();this.Ra=-1;k!=e||l!=h?this.$a("window-resize",{innerWidth:k,innerHeight:l,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Wa()}):10>d&&this.jg(k,l,d+1)}Xf(e){this.dd=e.targetOrientation}Dg(){const e=this.dd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(h=>console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(e):screen.webkitLockOrientation?
h=screen.webkitLockOrientation(e):screen.mozLockOrientation?h=screen.mozLockOrientation(e):screen.msLockOrientation&&(h=screen.msLockOrientation(e));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}Ya(){const e=f.Wa();e&&"any"!==this.dd&&this.Dg();u(this,"fullscreenchange",{isFullscreen:e,innerWidth:this.xa(),innerHeight:this.wa()})}Ic(e){console.warn("[Construct 3] Fullscreen request failed: ",e);u(this,"fullscreenerror",
{isFullscreen:f.Wa(),innerWidth:this.xa(),innerHeight:this.wa()})}Lc(e){e?this.A.zc():this.A.Nc();u(this,"visibilitychange",{hidden:e})}Gd(e,h){"Backspace"===h.key&&z(h);const d=b.get(h.code)||h.code;D(this,e,{code:d,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},c)}Pf(e){u(this,"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,deltaZ:e.deltaZ,deltaMode:e.deltaMode,
timeStamp:e.timeStamp},c)}Jc(e,h,d){a(h)||D(this,e,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,movementX:h.movementX||0,movementY:h.movementY||0,timeStamp:h.timeStamp},d)}Kc(e,h){if(!a(h)){var d=this.pb;"pointerdown"===e&&0!==d?e="pointermove":"pointerup"===e&&0!==h.buttons&&(e="pointermove");D(this,e,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:d,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,
movementX:h.movementX||0,movementY:h.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},c);this.pb=h.buttons;this.Jc(h.type,h,g)}}Za(e,h){if(this.sb&&"pointermove"!==e){var d=this.sb;d.hb||(L(d),d.Ub=Date.now())}d=0;"mouse"===h.pointerType&&(d=this.pb);D(this,e,{pointerId:h.pointerId,pointerType:h.pointerType,button:h.button,buttons:h.buttons,lastButtons:d,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,movementX:(h.movementX||
0)+this.ac,movementY:(h.movementY||0)+this.bc,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},c);this.bc=this.ac=0;"mouse"===h.pointerType&&(d="mousemove","pointerdown"===e?d="mousedown":"pointerup"===e&&(d="mouseup"),this.Jc(d,h,g),this.pb=h.buttons)}Qf(e){this.Ka&&(this.ac+=this.Ka.movementX||0,this.bc+=this.Ka.movementY||0);this.Ka=e;e=this.sb;if(-1===e.Sa){var h=Date.now(),
d=h-e.Ub,k=e.Jg;d>=k&&e.Rd?(e.Ub=h,e.hb=!0,e.Pc(),e.hb=!1):e.Sa=self.setTimeout(e.je,Math.max(k-d,4))}}kf(){this.Za("pointermove",this.Ka);this.Ka=null}Ib(e,h){for(let d=0,k=h.changedTouches.length;d<k;++d){const l=h.changedTouches[d];D(this,e,{pointerId:l.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,movementX:h.movementX||0,movementY:h.movementY||0,width:2*(l.radiusX||l.webkitRadiusX||0),height:2*(l.radiusY||l.webkitRadiusY||
0),pressure:l.force||l.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:l.rotationAngle||0,timeStamp:h.timeStamp},c)}}Ec(e){window!==window.top&&window.focus();this.Ed(e.target)&&document.activeElement&&!this.Ed(document.activeElement)&&document.activeElement.blur()}Ed(e){return!e||e===document||e===window||e===document.body||"canvas"===e.tagName.toLowerCase()}af(){this.Od||(this.Od=!0,window.addEventListener("deviceorientation",e=>this.Bf(e)),window.addEventListener("deviceorientationabsolute",
e=>this.Cf(e)))}$e(){this.Nd||(this.Nd=!0,window.addEventListener("devicemotion",e=>this.Af(e)))}Bf(e){u(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},c)}Cf(e){u(this,"deviceorientationabsolute",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},c)}Af(e){let h=null;var d=e.acceleration;d&&(h=
{x:d.x||0,y:d.y||0,z:d.z||0});d=null;var k=e.accelerationIncludingGravity;k&&(d={x:k.x||0,y:k.y||0,z:k.z||0});k=null;const l=e.rotationRate;l&&(k={alpha:l.alpha||0,beta:l.beta||0,gamma:l.gamma||0});u(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:d,rotationRate:k,interval:e.interval,timeStamp:e.timeStamp},c)}Zf(e){const h=this.A.G;h.style.width=e.styleWidth+"px";h.style.height=e.styleHeight+"px";h.style.marginLeft=e.marginLeft+"px";h.style.marginTop=e.marginTop+"px";this.Wd&&(h.style.display=
"",this.Wd=!1)}Lf(e){const h=e.url;e=e.filename;const d=document.createElement("a"),k=document.body;d.textContent=e;d.href=h;d.download=e;k.appendChild(d);d.click();k.removeChild(d)}async Sf(e){var h=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,e.surfaceHeight);h=h?await createImageBitmap(e,h):await createImageBitmap(e);return{imageBitmap:h,transferables:[h]}}async Jf(e){return await self.C3_GetSvgImageSize(e.blob)}async uf(e){await p(e.url)}Mc(){var e=
[...this.Ma];this.Ma.clear();if(!this.na)for(const h of e)(e=h.play())&&e.catch(()=>{this.Xb.has(h)||this.Ma.add(h)})}va(e){if("function"!==typeof e.play)throw Error("missing play function");this.Xb.delete(e);let h;try{h=e.play()}catch(d){this.Ma.add(e);return}h&&h.catch(()=>{this.Xb.has(e)||this.Ma.add(e)})}Fa(e){this.Ma.delete(e);this.Xb.add(e)}Db(e){this.na=!!e}Kf(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}zf(e){if(e.show){this.za||(this.za=document.createElement("div"),
this.za.id="inspectOutline",document.body.appendChild(this.za));var h=this.za;h.style.display="";h.style.left=e.left-1+"px";h.style.top=e.top-1+"px";h.style.width=e.width+2+"px";h.style.height=e.height+2+"px";h.textContent=e.name}else this.za&&(this.za.style.display="none")}Uf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Hd(e){window.c3_postToMessagePort&&(e.from="runtime",window.c3_postToMessagePort(e))}sf(e,h){return this.A.sd(this.bb,"js-invoke-function",{name:e,params:h},void 0,void 0)}vf(e){alert(e.message)}bg(e){"entered-fullscreen"===
e?(f.Md(!0),this.Ya()):"exited-fullscreen"===e?(f.Md(!1),this.Ya()):console.warn("Unknown wrapper message: ",e)}})}"use strict";async function Q(f){if(f.Ig)throw Error("already initialised");f.Ig=!0;var a=f.ec.Dc("dispatchworker.js");f.Rc=await f.ec.lc(a,f.F,{name:"DispatchWorker"});a=new MessageChannel;f.Vc=a.port1;f.Rc.postMessage({type:"_init","in-port":a.port2},[a.port2]);f.bd=await S(f)}function R(f){return[f.Vc,f.bd]}
async function S(f){const a=f.Yd.length;var b=f.ec.Dc("jobworker.js");b=await f.ec.lc(b,f.F,{name:"JobWorker"+a});const c=new MessageChannel,g=new MessageChannel;f.Rc.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);b.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":g.port2},[c.port2,g.port2]);f.Yd.push(b);return g.port1}
self.Me=class{constructor(f){this.ec=f;this.F=f.F;this.F="preview"===f.v?this.F+"workers/":this.F+f.fc;this.Lg=Math.min(navigator.hardwareConcurrency||2,16);this.Rc=null;this.Yd=[];this.bd=this.Vc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.ta({$g:!1,ah:"workermain.js",Ta:["scripts/c3runtime.js"],jc:[],fd:"",Xg:"scripts/",hd:[],ke:"html5"}));"use strict";
{const f=180/Math.PI;self.da=class extends self.Da{constructor(a){super(a,"audio");this.Qb=this.f=null;this.Sb=this.Uc=!1;this.qa=()=>this.Eg();this.aa=[];this.D=[];this.ga=null;this.Zd="";this.$d=-1;this.rb=new Map;this.Zc=1;this.na=!1;this.ed=0;this.hc=1;this.Sc=0;this.be="HRTF";this.Sd="inverse";this.ce=600;this.ae=1E4;this.ee=1;this.Ud=this.cd=!1;this.he=this.A.Ke();this.ba=new Map;this.Ia=new Set;this.Wc=!1;this.$c="";this.Aa=null;self.C3Audio_OnMicrophoneStream=(b,c)=>this.Of(b,c);this.Pb=null;
self.C3Audio_GetOutputStream=()=>this.If();self.C3Audio_DOMInterface=this;I(this,[["create-audio-context",b=>this.ff(b)],["play",b=>this.dg(b)],["stop",b=>this.Bg(b)],["stop-all",()=>this.Cg()],["set-paused",b=>this.ug(b)],["set-volume",b=>this.zg(b)],["fade-volume",b=>this.lf(b)],["set-master-volume",b=>this.sg(b)],["set-muted",b=>this.tg(b)],["set-silent",b=>this.wg(b)],["set-looping",b=>this.rg(b)],["set-playback-rate",b=>this.vg(b)],["seek",b=>this.kg(b)],["preload",b=>this.eg(b)],["unload",b=>
this.Fg(b)],["unload-all",()=>this.Gg()],["set-suspended",b=>this.xg(b)],["add-effect",b=>this.xd(b)],["set-effect-param",b=>this.og(b)],["remove-effects",b=>this.gg(b)],["tick",b=>this.Yf(b)],["load-state",b=>this.Mf(b)]])}async ff(a){a.isiOSCordova&&(this.cd=!0);this.ed=a.timeScaleMode;this.be=["equalpower","HRTF","soundfield"][a.panningModel];this.Sd=["linear","inverse","exponential"][a.distanceModel];this.ce=a.refDistance;this.ae=a.maxDistance;this.ee=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.he||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.yd();this.f.onstatechange=()=>{"running"!==this.f.state&&this.yd()};this.Qb=this.f.createGain();this.Qb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.mc();try{await Promise.all(a.preloadList.map(c=>this.Gb(c.originalUrl,c.url,c.type,!1)))}catch(c){console.error("[Construct 3] Preloading sounds failed: ",c)}return{sampleRate:this.f.sampleRate}}yd(){this.Sb||(this.Uc=!1,window.addEventListener("pointerup",this.qa,!0),window.addEventListener("touchend",this.qa,!0),window.addEventListener("click",this.qa,!0),window.addEventListener("keydown",this.qa,!0),this.Sb=!0)}hf(){this.Sb&&(this.Uc=!0,window.removeEventListener("pointerup",this.qa,!0),window.removeEventListener("touchend",
this.qa,!0),window.removeEventListener("click",this.qa,!0),window.removeEventListener("keydown",this.qa,!0),this.Sb=!1)}Eg(){if(!this.Uc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),c=a.createBufferSource();c.buffer=b;c.connect(a.destination);c.start(0);"running"===a.state&&this.hf()}}W(){return this.f}mc(){return this.f.currentTime}ra(){return this.Qb}pd(a){return(a=this.ba.get(a.toLowerCase()))?a[0].P():this.ra()}le(a,b){a=a.toLowerCase();let c=this.ba.get(a);
c||(c=[],this.ba.set(a,c));b.qg(c.length);b.yg(a);c.push(b);this.Kd(a)}Kd(a){let b=this.ra();const c=this.ba.get(a);if(c&&c.length){b=c[0].P();for(let g=0,m=c.length;g<m;++g){const p=c[g];g+1===m?p.S(this.ra()):p.S(c[g+1].P())}}for(const g of this.la(a))g.Re(b);this.Aa&&this.$c===a&&(this.Aa.disconnect(),this.Aa.connect(b))}zb(){return this.Zc}Ab(){return this.na}pg(){this.Ud=!0}Ee(a,b){return b?this.A.Hg(a).then(c=>{const g=this.f.createBuffer(1,c.length,48E3);g.getChannelData(0).set(c);return g}):
new Promise((c,g)=>{this.f.decodeAudioData(a,c,g)})}va(a){this.A.va(a)}Fa(a){this.A.Fa(a)}td(a){let b=0;for(let c=0,g=this.D.length;c<g;++c){const m=this.D[c];this.D[b]=m;m.L===a?m.c():++b}this.D.length=b}Se(){let a=0;for(let b=0,c=this.aa.length;b<c;++b){const g=this.aa[b];this.aa[a]=g;g.sa()?g.c():++a}this.aa.length=a}*la(a){if(a)for(const b of this.D)self.da.Fe(b.Z,a)&&(yield b);else this.ga&&!this.ga.T()&&(yield this.ga)}async Gb(a,b,c,g,m){for(const p of this.aa)if(p.Va()===b)return await T(p),
p;if(m)return null;g&&(this.cd||this.Ud)&&this.Se();m="audio/webm; codecs=opus"===c&&!this.he;g&&m&&this.pg();a=!g||this.cd||m?new self.ze(this,a,b,c,g,m):new self.xe(this,a,b,c,g);this.aa.push(a);await T(a);return a}async Bc(a,b,c,g,m){for(const p of this.D)if(p.Va()===b&&(p.kc()||m))return p.Ue(g),p;a=await this.Gb(a,b,c,m);g="html5"===a.Oc?new self.ye(a.i,a,g):new self.Ae(a.i,a,g);this.D.push(g);return g}Ye(a){let b=this.rb.get(a);if(!b){let c=null;b={gd:0,Wg:new Promise(g=>c=g),resolve:c};this.rb.set(a,
b)}b.gd++}hg(a){const b=this.rb.get(a);if(!b)throw Error("expected pending tag");b.gd--;0===b.gd&&(b.resolve(),this.rb.delete(a))}xc(a){a||(a=this.Zd);return(a=this.rb.get(a))?a.Wg:Promise.resolve()}Hb(){if(0<this.Ia.size)J(this);else for(const a of this.D)if(a.qd()){J(this);break}}ua(){for(var a of this.Ia)a.ua();a=this.mc();for(var b of this.D)b.ua(a);b=this.D.filter(c=>c.qd()).map(c=>c.Ua());u(this,"state",{tickCount:this.$d,audioInstances:b,analysers:[...this.Ia].map(c=>c.He())});0===b.length&&
0===this.Ia.size&&this.Tb&&(this.A.ig(this.ie),this.Tb=!1)}tc(a,b,c){u(this,"trigger",{type:a,tag:b,aiid:c})}async dg(a){const b=a.originalUrl,c=a.url,g=a.type,m=a.isMusic,p=a.tag,x=a.isLooping,A=a.vol,B=a.pos,v=a.panning;let w=a.off;0<w&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),w=w-a.performanceTime/1E3+a.contextTime):w=w-performance.now()/1E3+this.f.currentTime);this.Zd=p;this.Ye(p);try{this.ga=await this.Bc(b,c,g,p,m),v?(this.ga.Cb(!0),this.ga.Te(v.x,v.y,v.angle,
v.innerAngle,v.outerAngle,v.outerGain),v.hasOwnProperty("uid")&&this.ga.Ve(v.uid)):this.ga.Cb(!1),this.ga.Play(x,A,B,w)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.hg(p)}J(this)}Bg(a){a=a.tag;for(const b of this.la(a))b.ma()}Cg(){for(const a of this.D)a.ma()}ug(a){const b=a.tag;a=a.paused;for(const c of this.la(b))a?c.Xa():c.Bb();this.Hb()}zg(a){const b=a.tag;a=a.vol;for(const c of this.la(b))c.Eb(a)}async lf(a){const b=a.tag,c=a.vol,g=a.duration;
a=a.stopOnEnd;await this.xc(b);for(const m of this.la(b))m.Ge(c,g,a);this.Hb()}sg(a){this.Zc=a.vol;for(const b of this.D)b.Mb()}tg(a){const b=a.tag;a=a.isMuted;for(const c of this.la(b))c.ud(a)}wg(a){this.na=a.isSilent;this.A.Db(this.na);for(const b of this.D)b.Lb()}rg(a){const b=a.tag;a=a.isLooping;for(const c of this.la(b))c.vc(a)}async vg(a){const b=a.tag;a=a.rate;await this.xc(b);for(const c of this.la(b))c.wd(a)}async kg(a){const b=a.tag;a=a.pos;await this.xc(b);for(const c of this.la(b))c.uc(a)}async eg(a){const b=
a.originalUrl,c=a.url,g=a.type;a=a.isMusic;try{await this.Bc(b,c,g,"",a)}catch(m){console.error("[Construct 3] Audio: error preloading: ",m)}}async Fg(a){if(a=await this.Gb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.aa.indexOf(a),-1!==a&&this.aa.splice(a,1)}Gg(){for(const a of this.aa)a.c();this.aa.length=0}xg(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.D)b.wc(a);a&&this.f.suspend&&this.f.suspend()}Yf(a){this.hc=a.timeScale;this.Sc=a.gameTime;this.$d=a.tickCount;if(0!==
this.ed)for(var b of this.D)b.Ha();(b=a.listenerPos)&&this.f.listener.setPosition(b[0],b[1],b[2]);for(const c of a.instPans){a=c.uid;for(const g of this.D)g.fa===a&&g.vd(c.x,c.y,c.angle)}}async xd(a){var b=a.type;const c=a.tag;var g=a.params;if("filter"===b)g=new self.re(this,...g);else if("delay"===b)g=new self.pe(this,...g);else if("convolution"===b){b=null;try{b=await this.Gb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct 3] Audio: error loading convolution: ",
m);return}g=new self.oe(this,b.$,...g);g.mg(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)g=new self.se(this,...g);else if("phaser"===b)g=new self.ue(this,...g);else if("gain"===b)g=new self.te(this,...g);else if("tremolo"===b)g=new self.we(this,...g);else if("ringmod"===b)g=new self.ve(this,...g);else if("distortion"===b)g=new self.qe(this,...g);else if("compressor"===b)g=new self.ne(this,...g);else if("analyser"===b)g=new self.me(this,...g);else throw Error("invalid effect type");this.le(c,
g);this.Jd()}og(a){const b=a.index,c=a.param,g=a.value,m=a.ramp,p=a.time;a=this.ba.get(a.tag);!a||0>b||b>=a.length||(a[b].X(c,g,m,p),this.Jd())}gg(a){a=a.tag.toLowerCase();const b=this.ba.get(a);if(b&&b.length){for(const c of b)c.c();this.ba.delete(a);this.Kd(a)}}Xe(a){this.Ia.add(a);this.Hb()}fg(a){this.Ia.delete(a)}Jd(){this.Wc||(this.Wc=!0,Promise.resolve().then(()=>this.jf()))}jf(){const a={};for(const [b,c]of this.ba)a[b]=c.map(g=>g.Ua());u(this,"fxstate",{fxstate:a});this.Wc=!1}async Mf(a){const b=
a.saveLoadMode;if(3!==b)for(var c of this.D)c.sa()&&1===b||(c.sa()||2!==b)&&c.ma();for(const g of this.ba.values())for(const m of g)m.c();this.ba.clear();this.hc=a.timeScale;this.Sc=a.gameTime;c=a.listenerPos;this.f.listener.setPosition(c[0],c[1],c[2]);this.na=a.isSilent;this.A.Db(this.na);this.Zc=a.masterVolume;c=[];for(const g of Object.values(a.effects))c.push(Promise.all(g.map(m=>this.xd(m))));await Promise.all(c);await Promise.all(a.playing.map(g=>this.tf(g,b)));this.Hb()}async tf(a,b){if(3!==
b){var c=a.bufferOriginalUrl,g=a.bufferUrl,m=a.bufferType,p=a.isMusic,x=a.tag,A=a.isLooping,B=a.volume,v=a.playbackTime;if(!p||1!==b)if(p||2!==b){b=null;try{b=await this.Bc(c,g,m,x,p)}catch(w){console.error("[Construct 3] Audio: error loading audio state: ",w);return}b.Pe(a.pan);b.Play(A,B,v,0);a.isPlaying||b.Xa();b.Gc(a)}}}Of(a,b){this.Aa&&this.Aa.disconnect();this.$c=b.toLowerCase();this.Aa=this.f.createMediaStreamSource(a);this.Aa.connect(this.pd(this.$c))}If(){this.Pb||(this.Pb=this.f.createMediaStreamDestination(),
this.Qb.connect(this.Pb));return this.Pb.stream}static Fe(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static We(a){return a*f}static De(a){return Math.pow(10,a/20)}static od(a){return Math.max(Math.min(self.da.De(a),1),0)}static Oe(a){return Math.log(a)/Math.log(10)*20}static Ne(a){return self.da.Oe(Math.max(Math.min(a,1),0))}static Rg(a,b){return 1-Math.exp(-b*a)}};self.ta.Ca(self.da)}"use strict";function T(f){f.Vb||(f.Vb=f.Fc());return f.Vb}
self.kd=class{constructor(f,a,b,c,g){this.i=f;this.Ng=a;this.Ba=b;this.R=c;this.Kg=g;this.Oc="";this.Vb=null}c(){this.Vb=this.i=null}Fc(){}W(){return this.i.W()}oc(){return this.Ng}Va(){return this.Ba}nc(){return this.R}sa(){return this.Kg}ea(){}};"use strict";
self.xe=class extends self.kd{constructor(f,a,b,c,g){super(f,a,b,c,g);this.Oc="html5";this.K=new Audio;this.K.crossOrigin="anonymous";this.K.autoplay=!1;this.K.preload="auto";this.lb=this.mb=null;this.K.addEventListener("canplaythrough",()=>!0);this.qb=this.W().createGain();this.ob=null;this.K.addEventListener("canplay",()=>{this.mb&&(this.mb(),this.lb=this.mb=null);!this.ob&&this.K&&(this.ob=this.W().createMediaElementSource(this.K),this.ob.connect(this.qb))});this.onended=null;this.K.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.K.addEventListener("error",m=>{console.error(`[Construct 3] Audio '${this.Ba}' error: `,m);this.lb&&(this.lb(m),this.lb=this.mb=null)})}c(){this.i.td(this);this.qb.disconnect();this.qb=null;this.ob.disconnect();this.ob=null;this.K&&!this.K.paused&&this.K.pause();this.K=this.onended=null;super.c()}Fc(){return new Promise((f,a)=>{this.mb=f;this.lb=a;this.K.src=this.Ba})}O(){return this.K}ea(){return this.K.duration}};"use strict";
async function U(f){if(f.ya)return f.ya;var a=f.i.A;if("cordova"===a.v&&a.rd(f.Ba)&&a.ib)f.ya=await a.xb(f.Ba);else{a=await fetch(f.Ba);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);f.ya=await a.arrayBuffer()}}async function V(f){if(f.$)return f.$;f.$=await f.i.Ee(f.ya,f.Mg);f.ya=null}
self.ze=class extends self.kd{constructor(f,a,b,c,g,m){super(f,a,b,c,g);this.Oc="webaudio";this.$=this.ya=null;this.Mg=!!m}c(){this.i.td(this);this.$=this.ya=null;super.c()}async Fc(){try{await U(this),await V(this)}catch(f){console.error(`[Construct 3] Failed to load audio '${this.Ba}': `,f)}}ea(){return this.$?this.$.duration:0}};"use strict";
{let f=0;self.ld=class{constructor(a,b,c){this.i=a;this.L=b;this.Z=c;this.Nb=f++;this.M=this.W().createGain();this.M.connect(this.ra());this.B=null;this.jb=!1;this.ja=[0,0,0];this.ia=[0,0,0];this.I=!0;this.V=this.ka=this.H=!1;this.ub=1;this.Ja=!1;this.pa=1;a=this.i.ed;this.Yc=1===a&&!this.sa()||2===a;this.fb=this.fa=-1;this.ge=!1}c(){this.L=this.i=null;this.B&&(this.B.disconnect(),this.B=null);this.M.disconnect();this.M=null}W(){return this.i.W()}ra(){return this.i.pd(this.Z)}zb(){return this.i.zb()}yb(){return this.Yc?
this.i.Sc:performance.now()/1E3}oc(){return this.L.oc()}Va(){return this.L.Va()}nc(){return this.L.nc()}sa(){return this.L.sa()}Ue(a){this.Z=a}T(){}kc(){}IsPlaying(){return!this.I&&!this.H&&!this.T()}qd(){return!this.I&&!this.T()}Ea(){}ea(){return this.L.ea()}Play(){}ma(){}Xa(){}Bb(){}Eb(a){this.ub=a;this.M.gain.cancelScheduledValues(0);this.fb=-1;this.M.gain.value=this.pc()}Ge(a,b,c){if(!this.Ja){a*=this.zb();var g=this.M.gain;g.cancelScheduledValues(0);var m=this.i.mc();b=m+b;g.setValueAtTime(g.value,
m);g.linearRampToValueAtTime(a,b);this.ub=a;this.fb=b;this.ge=c}}Mb(){this.Eb(this.ub)}ua(a){-1!==this.fb&&a>=this.fb&&(this.fb=-1,this.ge&&this.ma(),this.i.tc("fade-ended",this.Z,this.Nb))}pc(){const a=this.ub*this.zb();return isFinite(a)?a:0}ud(a){a=!!a;this.Ja!==a&&(this.Ja=a,this.Lb())}Ab(){return this.i.Ab()}Lb(){}vc(){}wd(a){this.pa!==a&&(this.pa=a,this.Ha())}Ha(){}uc(){}wc(){}Cb(a){a=!!a;this.jb!==a&&((this.jb=a)?(this.B||(this.B=this.W().createPanner(),this.B.panningModel=this.i.be,this.B.distanceModel=
this.i.Sd,this.B.refDistance=this.i.ce,this.B.maxDistance=this.i.ae,this.B.rolloffFactor=this.i.ee),this.M.disconnect(),this.M.connect(this.B),this.B.connect(this.ra())):(this.B.disconnect(),this.M.disconnect(),this.M.connect(this.ra())))}Te(a,b,c,g,m,p){this.jb&&(this.vd(a,b,c),a=self.da.We,this.B.coneInnerAngle=a(g),this.B.coneOuterAngle=a(m),this.B.coneOuterGain=p)}vd(a,b,c){this.jb&&(this.ja[0]=a,this.ja[1]=b,this.ja[2]=0,this.ia[0]=Math.cos(c),this.ia[1]=Math.sin(c),this.ia[2]=0,this.B.setPosition(...this.ja),
this.B.setOrientation(...this.ia))}Ve(a){this.fa=a}qc(){}Re(a){const b=this.B||this.M;b.disconnect();b.connect(a)}Ua(){return{aiid:this.Nb,tag:this.Z,duration:this.ea(),volume:this.ub,isPlaying:this.IsPlaying(),playbackTime:this.Ea(),playbackRate:this.pa,uid:this.fa,bufferOriginalUrl:this.oc(),bufferUrl:"",bufferType:this.nc(),isMusic:this.sa(),isLooping:this.V,isMuted:this.Ja,resumePosition:this.qc(),pan:this.Ie()}}Gc(a){this.wd(a.playbackRate);this.ud(a.isMuted)}Ie(){if(!this.B)return null;const a=
this.B;return{pos:this.ja,orient:this.ia,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.fa}}Pe(a){if(a){this.Cb(!0);a=this.B;var b=a.pos;this.ja[0]=b[0];this.ja[1]=b[1];this.ja[2]=b[2];b=a.orient;this.ia[0]=b[0];this.ia[1]=b[1];this.ia[2]=b[2];a.setPosition(...this.ja);a.setOrientation(...this.ia);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.fa=a.uid}else this.Cb(!1)}}}"use strict";
self.ye=class extends self.ld{constructor(f,a,b){super(f,a,b);this.L.qb.connect(this.M);this.L.onended=()=>this.Hc()}c(){this.ma();this.L.qb.disconnect();super.c()}O(){return this.L.O()}Hc(){this.I=!0;this.fa=-1;this.i.tc("ended",this.Z,this.Nb)}T(){return this.O().ended}kc(){return this.I?!0:this.T()}Ea(){let f=this.O().currentTime;this.V||(f=Math.min(f,this.ea()));return f}Play(f,a,b){const c=this.O();1!==c.playbackRate&&(c.playbackRate=1);c.loop!==f&&(c.loop=f);this.Eb(a);c.muted&&(c.muted=!1);
if(c.currentTime!==b)try{c.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.L.Va()}' to position '${b}': `,g)}this.i.va(c);this.H=this.I=!1;this.V=f;this.pa=1}ma(){const f=this.O();f.paused||f.pause();this.i.Fa(f);this.I=!0;this.H=!1;this.fa=-1}Xa(){if(!(this.H||this.I||this.T())){var f=this.O();f.paused||f.pause();this.i.Fa(f);this.H=!0}}Bb(){!this.H||this.I||this.T()||(this.i.va(this.O()),this.H=!1)}Lb(){this.O().muted=this.Ja||this.Ab()}vc(f){f=!!f;this.V!==f&&
(this.V=f,this.O().loop=f)}Ha(){let f=this.pa;this.Yc&&(f*=this.i.hc);try{this.O().playbackRate=f}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${f}':`,a)}}uc(f){if(!this.I&&!this.T())try{this.O().currentTime=f}catch(a){console.warn(`[Construct 3] Error seeking audio to '${f}': `,a)}}qc(){return this.Ea()}wc(f){f?this.IsPlaying()?(this.O().pause(),this.ka=!0):this.ka=!1:this.ka&&(this.i.va(this.O()),this.ka=!1)}};"use strict";
function W(f){f.j&&f.j.disconnect();f.j=null;f.ab=null}
self.Ae=class extends self.ld{constructor(f,a,b){super(f,a,b);this.j=null;this.Yb=c=>this.Hc(c);this.Tc=!0;this.ab=null;this.N=this.Zb=this.$b=0;this.ad=1}c(){this.ma();W(this);this.Yb=null;super.c()}Hc(f){this.H||this.ka||f.target!==this.ab||(this.I=this.Tc=!0,this.fa=-1,W(this),this.i.tc("ended",this.Z,this.Nb))}T(){return!this.I&&this.j&&this.j.loop||this.H?!1:this.Tc}kc(){return!this.j||this.I?!0:this.T()}Ea(){let f;f=this.H?this.N:this.Zb+(this.yb()-this.$b)*this.pa;this.V||(f=Math.min(f,this.ea()));
return f}Play(f,a,b,c){this.ad=1;this.Eb(a);W(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.$;this.j.connect(this.M);this.ab=this.j;this.j.onended=this.Yb;this.j.loop=f;this.j.start(c,b);this.H=this.I=this.Tc=!1;this.V=f;this.pa=1;this.$b=this.yb();this.Zb=b}ma(){if(this.j)try{this.j.stop(0)}catch(f){}this.I=!0;this.H=!1;this.fa=-1}Xa(){this.H||this.I||this.T()||(this.N=this.Ea(),this.V&&(this.N%=this.ea()),this.H=!0,this.j.stop(0))}Bb(){!this.H||this.I||this.T()||(W(this),this.j=
this.W().createBufferSource(),this.j.buffer=this.L.$,this.j.connect(this.M),this.ab=this.j,this.j.onended=this.Yb,this.j.loop=this.V,this.Mb(),this.Ha(),this.j.start(0,this.N),this.$b=this.yb(),this.Zb=this.N,this.H=!1)}pc(){return super.pc()*this.ad}Lb(){this.ad=this.Ja||this.Ab()?0:1;this.Mb()}vc(f){f=!!f;this.V!==f&&(this.V=f,this.j&&(this.j.loop=f))}Ha(){let f=this.pa;this.Yc&&(f*=this.i.hc);this.j&&(this.j.playbackRate.value=f)}uc(f){this.I||this.T()||(this.H?this.N=f:(this.Xa(),this.N=f,this.Bb()))}qc(){return this.N}wc(f){f?
this.IsPlaying()?(this.ka=!0,this.N=this.Ea(),this.V&&(this.N%=this.ea()),this.j.stop(0)):this.ka=!1:this.ka&&(W(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.$,this.j.connect(this.M),this.ab=this.j,this.j.onended=this.Yb,this.j.loop=this.V,this.Mb(),this.Ha(),this.j.start(0,this.N),this.$b=this.yb(),this.Zb=this.N,this.ka=!1)}Gc(f){super.Gc(f);this.N=f.resumePosition}};"use strict";
{class f{constructor(a){this.i=a;this.f=a.W();this.Vd=-1;this.R=this.Z="";this.g=null}c(){this.f=null}qg(a){this.Vd=a}yg(a){this.Z=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,c,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var m=this.f.currentTime;g+=m;switch(c){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,m);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,m),a.exponentialRampToValueAtTime(b,g)}}}Ua(){return{type:this.R,tag:this.Z,params:this.g}}}
self.re=class extends f{constructor(a,b,c,g,m,p,x){super(a);this.R="filter";this.g=[b,c,g,m,p,x];this.l=this.o();this.b=this.o();this.b.gain.value=x;this.a=this.o();this.a.gain.value=1-x;this.u=this.f.createBiquadFilter();this.u.type=b;this.u.frequency.value=c;this.u.detune.value=g;this.u.Q.value=m;this.u.gain.vlaue=p;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b)}c(){this.l.disconnect();this.u.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,c,g);this.m(this.a.gain,1-b,c,g);break;case 1:this.g[1]=b;this.m(this.u.frequency,b,c,g);break;case 2:this.g[2]=b;this.m(this.u.detune,b,c,g);break;case 3:this.g[3]=b;this.m(this.u.Q,b,c,g);break;case 4:this.g[4]=b,this.m(this.u.gain,b,c,g)}}};self.pe=class extends f{constructor(a,b,c,g){super(a);this.R="delay";this.g=[b,c,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.nb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.eb=this.o();this.eb.gain.value=c;this.l.connect(this.nb);this.l.connect(this.a);this.nb.connect(this.b);this.nb.connect(this.U);this.U.connect(this.eb);this.eb.connect(this.nb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.nb.disconnect();this.U.disconnect();this.eb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){const m=self.da.od;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,c,g);this.m(this.a.gain,1-b,c,g);break;case 4:this.g[1]=m(b);this.m(this.eb.gain,m(b),c,g);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,c,g)}}};self.oe=class extends f{constructor(a,b,c,g){super(a);this.R="convolution";this.g=[c,g];this.Qd=this.Pd="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.cb=this.f.createConvolver();this.cb.normalize=c;this.cb.buffer=b;this.l.connect(this.cb);this.l.connect(this.a);this.cb.connect(this.b)}c(){this.l.disconnect();this.cb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,c,g),this.m(this.a.gain,1-b,c,g)}}mg(a,b){this.Pd=a;this.Qd=b}Ua(){const a=
super.Ua();a.bufferOriginalUrl=this.Pd;a.bufferUrl="";a.bufferType=this.Qd;return a}};self.se=class extends f{constructor(a,b,c,g,m,p){super(a);this.R="flanger";this.g=[b,c,g,m,p];this.l=this.o();this.a=this.o();this.a.gain.value=1-p/2;this.b=this.o();this.b.gain.value=p/2;this.gb=this.o();this.gb.gain.value=m;this.U=this.f.createDelay(b+c);this.U.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=g;this.J=this.o();this.J.gain.value=c;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.gb);this.gb.connect(this.U);this.s.connect(this.J);this.J.connect(this.U.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.U.disconnect();this.s.disconnect();this.J.disconnect();this.a.disconnect();this.b.disconnect();this.gb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,c,g);this.m(this.a.gain,1-b/2,c,g);break;case 6:this.g[1]=b/1E3;this.m(this.J.gain,b/1E3,c,g);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,c,g);break;case 8:this.g[3]=b/100,this.m(this.gb.gain,b/100,c,g)}}};self.ue=class extends f{constructor(a,b,c,g,m,p,x){super(a);this.R="phaser";this.g=[b,c,g,m,p,x];this.l=this.o();this.a=this.o();this.a.gain.value=1-x/2;this.b=this.o();this.b.gain.value=x/2;this.u=this.f.createBiquadFilter();this.u.type="allpass";this.u.frequency.value=b;this.u.detune.value=
c;this.u.Q.value=g;this.s=this.f.createOscillator();this.s.frequency.value=p;this.J=this.o();this.J.gain.value=m;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b);this.s.connect(this.J);this.J.connect(this.u.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.u.disconnect();this.s.disconnect();this.J.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,c,g);this.m(this.a.gain,1-b/2,c,g);break;case 1:this.g[0]=b;this.m(this.u.frequency,b,c,g);break;case 2:this.g[1]=b;this.m(this.u.detune,b,c,g);break;case 3:this.g[2]=b;this.m(this.u.Q,b,c,g);break;case 6:this.g[3]=b;this.m(this.J.gain,b,c,g);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,c,g)}}};self.te=class extends f{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,c,g){const m=self.da.od;switch(a){case 4:this.g[0]=m(b),this.m(this.h.gain,m(b),c,g)}}};self.we=class extends f{constructor(a,b,c){super(a);this.R="tremolo";this.g=[b,c];this.h=this.o();this.h.gain.value=1-c/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.J=this.o();this.J.gain.value=c/2;this.s.connect(this.J);this.J.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.J.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,c,g);this.m(this.J.gain,b/2,c,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,g)}}};self.ve=class extends f{constructor(a,b,c){super(a);this.R="ringmod";this.g=[b,c];this.l=this.o();this.b=this.o();this.b.gain.value=c;this.a=this.o();this.a.gain.value=1-c;this.tb=this.o();this.tb.gain.value=
0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.tb.gain);this.s.start(0);this.l.connect(this.tb);this.l.connect(this.a);this.tb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.tb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,c,g);
this.m(this.a.gain,1-b,c,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,g)}}};self.qe=class extends f{constructor(a,b,c,g,m,p){super(a);this.R="distortion";this.g=[b,c,g,m,p];this.l=this.o();this.dc=this.o();this.cc=this.o();this.ng(g,m);this.b=this.o();this.b.gain.value=p;this.a=this.o();this.a.gain.value=1-p;this.ic=this.f.createWaveShaper();this.Qc=new Float32Array(65536);this.nf(b,c);this.ic.curve=this.Qc;this.l.connect(this.dc);this.l.connect(this.a);this.dc.connect(this.ic);this.ic.connect(this.cc);
this.cc.connect(this.b)}c(){this.l.disconnect();this.dc.disconnect();this.ic.disconnect();this.cc.disconnect();this.b.disconnect();this.a.disconnect();super.c()}ng(a,b){.01>a&&(a=.01);this.dc.gain.value=a;this.cc.gain.value=Math.pow(1/a,.6)*b}nf(a,b){for(let c=0;32768>c;++c){let g=c/32768;g=this.Ag(g,a,b);this.Qc[32768+c]=g;this.Qc[32768-c-1]=-g}}Ag(a,b,c){c=1.05*c*b-b;const g=0>a?-a:a;return(g<b?g:b+c*self.da.Rg(g-b,1/c))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,c,g),this.m(this.a.gain,1-b,c,g)}}};self.ne=class extends f{constructor(a,b,c,g,m,p){super(a);this.R="compressor";this.g=[b,c,g,m,p];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=c;this.h.ratio.value=g;this.h.attack.value=m;this.h.release.value=p}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.me=class extends f{constructor(a,b,c){super(a);this.R="analyser";this.g=[b,c];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=c;this.Td=new Float32Array(this.h.frequencyBinCount);this.fe=new Uint8Array(b);this.de=this.Na=0;this.i.Xe(this)}c(){this.i.fg(this);this.h.disconnect();super.c()}ua(){this.h.getFloatFrequencyData(this.Td);this.h.getByteTimeDomainData(this.fe);const a=this.h.fftSize;let b=this.Na=0;for(var c=0;c<a;++c){let g=(this.fe[c]-128)/128;0>g&&(g=-g);
this.Na<g&&(this.Na=g);b+=g*g}c=self.da.Ne;this.Na=c(this.Na);this.de=c(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}He(){return{tag:this.Z,index:this.Vd,peak:this.Na,rms:this.de,binCount:this.h.frequencyBinCount,freqBins:this.Td}}}}"use strict";
{function f(a){a.stopPropagation()}self.ta.Ca(class extends self.Ce{constructor(a){super(a,"button")}nd(a,b){const c=document.createElement("input");var g=c;b.isCheckbox?(c.type="checkbox",g=document.createElement("label"),g.appendChild(c),g.appendChild(document.createTextNode("")),g.style.fontFamily="sans-serif",g.style.userSelect="none",g.style.webkitUserSelect="none",g.style.display="inline-block",g.style.color="black"):c.type="button";g.style.position="absolute";g.addEventListener("touchstart",
f);g.addEventListener("touchmove",f);g.addEventListener("touchend",f);g.addEventListener("mousedown",f);g.addEventListener("mouseup",f);g.addEventListener("keydown",f);g.addEventListener("keyup",f);c.addEventListener("click",()=>{var m={isChecked:c.checked};m.elementId=a;D(this,"click",m)});b.id&&(c.id=b.id);this.yc(g,b);return g}Cd(a){return"input"===a.tagName.toLowerCase()?a:a.firstChild}Cc(a){return this.Cd(a)}yc(a,b){const c=this.Cd(a);c.checked=b.isChecked;c.disabled=!b.isEnabled;a.title=b.title;
a===c?c.value=b.text:a.lastChild.textContent=b.text}})}"use strict";
{let f=!1;self.ta.Ca(class extends self.Da{constructor(a){super(a,"gamepad");this.Xd=!!navigator.getGamepads;this.Xc=!1;E(this,"is-supported",()=>this.Xd);E(this,"ready",()=>this.Tf());E(this,"vibrate",b=>this.Hf(b));E(this,"reset-vibrate",b=>this.Gf(b));window.addEventListener("gamepadconnected",b=>this.Ef(b));window.addEventListener("gamepaddisconnected",b=>this.Ff(b));window.addEventListener("unload",()=>this.ag())}Fb(){try{return Array.from(navigator.getGamepads()).filter(a=>a&&a.connected)}catch(a){return f||
(console.warn("[Construct 3] Failed to access gamepads: ",a),f=!0),[]}}Tf(){this.Xc=!0;for(const a of this.Fb())u(this,"gamepad-connected",{index:a.index,id:a.id});this.Xd&&J(this)}Ef(a){this.Xc&&(a=a.gamepad,u(this,"gamepad-connected",{index:a.index,id:a.id}))}Ff(a){this.Xc&&u(this,"gamepad-disconnected",{index:a.gamepad.index})}ua(){var a=this.Fb();a.length&&(a=a.map(b=>({index:b.index,id:b.id,buttons:b.buttons.map(c=>({pressed:c.pressed,value:c.value})),axes:b.axes})),u(this,"input-update",a))}Bd(a){for(const b of this.Fb())if(b.index===
a)return b;return null}async Hf(a){var b=this.Bd(a.index);if(b&&(b=b.vibrationActuator)&&b.playEffect)try{await b.playEffect("dual-rumble",{duration:a.duration,startDelay:0,weakMagnitude:a.weakMag,strongMagnitude:a.strongMag})}catch(c){console.warn("[Gamepad] Failed to vibrate gamepad: ",c)}}Gf(a){(a=this.Bd(a.index))&&(a=a.vibrationActuator)&&a.reset&&a.reset()}ag(){for(const a of this.Fb()){const b=a.vibrationActuator;b&&b.reset&&b.reset()}}})}"use strict";
self.ta.Ca(class extends self.Da{constructor(f){super(f,"mouse");I(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.A.G.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{u(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{u(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";async function X(f,a){a=a.type;let b=!0;0===a?b=await Y():1===a&&(b=await Z());u(f,"permission-result",{type:a,result:b})}async function Y(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request orientation permission: ",f),!1}}
async function Z(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request motion permission: ",f),!1}}self.ta.Ca(class extends self.Da{constructor(f){super(f,"touch");E(this,"request-permission",a=>X(this,a))}});
